import assert from 'node:assert/strict';
import {visibleWidth} from '@earendil-works/pi-tui';
import type {Block} from '../../src/types';
import {runHerdrScenario} from './herdr-runner';

const result = await runHerdrScenario({name:'compact-chrome', async prepare(){}, async run(s){
  const terminal = await s.attachClient();
  await terminal.resize(180,60);
  const parent = await s.client.request<Block>({action:'create',text:'CHROME CONTEXT'});
  const note = await s.client.request<Block>({action:'create',parentId:parent.id,text:[
    'CHROME READING PLAN', '[stage::queued]', '', '## Start here',
    'A short paragraph that should have room to breathe.', '',
    ...Array.from({length:30},(_,i)=>`Reading line ${i+1}`),
  ].join('\n')});
  const clients = await s.registrations();
  const tree = clients.find(c=>c.runtime?.paneId===s.panes.tree)!;
  const detail = clients.find(c=>c.runtime?.paneId===s.panes.detail)!;
  await s.client.request({action:'navigation.dispatch',sourceClientId:tree.clientId,sourceRegion:'tree',intent:'open',target:{kind:'block',blockId:note.id},destination:{clientId:detail.clientId,region:'detail'}});
  await s.focus(s.panes.detail);
  await s.waitVisible(s.panes.detail,'Start here');
  await s.waitFor('ordinary receipt retires',()=>s.visible(s.panes.detail),f=>!f.includes('Opened here'));
  await s.waitFor('host title removes duplicate chrome title',()=>s.visible(s.panes.detail),f=>!f.split('\n')[0]!.includes('CHROME READING PLAN'));
  assert.equal((await s.panePresentation(s.panes.detail)).title,'CHROME READING PLAN');
  let frame = await s.visible(s.panes.detail);
  assert.ok(!frame.includes('Opens in:'));
  assert.ok(!frame.includes('Collapsed · press b'));
  assert.ok(frame.split('\n').findIndex(line=>line.includes('CHROME READING PLAN'))<=2);
  await s.checkpoint('01-compact-detail');
  const click = async(label:string)=>{
    const frame = await s.waitFor('pointer target '+label,()=>terminal.visible(),f=>f.split('\n').some(line=>line.includes('● Current')&&line.includes(label)));
    const lines=frame.split('\n');
    const row=lines.findIndex(line=>line.includes('● Current')&&line.includes(label));
    const column=visibleWidth(lines[row]!.slice(0,lines[row]!.indexOf(label)));
    await terminal.write(`\x1b[<0;${column+2};${row+1}M\x1b[<0;${column+2};${row+1}m`);
  };
  await click('[View]');
  await s.waitVisible(s.panes.detail,'Detail chrome');
  await s.text(s.panes.detail,'Detail chrome');
  await s.keys(s.panes.detail,'enter');
  await s.waitFor('full Detail chrome',()=>s.visible(s.panes.detail),f=>f.includes('Opens in:')&&!f.includes('Find:'));
  await s.checkpoint('02-expanded-detail');
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.text(s.panes.detail,'Detail chrome');
  await s.keys(s.panes.detail,'enter');
  await s.waitFor('compact restored',()=>s.visible(s.panes.detail),f=>!f.includes('Opens in:')&&f.includes('Start here'));
  await terminal.write('\x1b[6~');
  const scrolled = await s.waitFor('scrolled into prose',()=>s.visible(s.panes.detail),f=>f.split('\n')[1]!.startsWith('Reading line'));
  const anchor = scrolled.split('\n')[1]!;
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.text(s.panes.detail,'Detail chrome');
  await s.keys(s.panes.detail,'enter');
  await s.waitFor('full Detail chrome',()=>s.visible(s.panes.detail),f=>f.includes('Opens in:')&&!f.includes('Find:'));
  assert.equal((await s.visible(s.panes.detail)).split('\n')[3],anchor,'Expanded keeps the same authored text at the top');
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.text(s.panes.detail,'Detail chrome');
  await s.keys(s.panes.detail,'enter');
  await s.waitFor('compact returns to the same reading position',()=>s.visible(s.panes.detail),f=>f.split('\n')[1]===anchor);
  await s.keys(s.panes.detail,'g');
  await s.waitVisible(s.panes.detail,'Start here');
  await s.setKeybindings({'detail.property.toggle':['Alt+9']});
  await s.keys(s.panes.detail,'ctrl+r');
  await s.waitVisible(s.panes.detail,'Keymap and bars reloaded');
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.text(s.panes.detail,'properties');
  await s.waitVisible(s.panes.detail,'⌥9');
  await s.keys(s.panes.detail,'esc');
  await s.keys(s.panes.detail,'alt+9');
  await s.waitVisible(s.panes.detail,'queued');
  await s.checkpoint('03-explicit-properties');
  await s.keys(s.panes.detail,'alt+9');
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.text(s.panes.detail,'Location / ancestors');
  await s.keys(s.panes.detail,'enter');
  await s.waitVisible(s.panes.detail,'CHROME CONTEXT');
  await s.keys(s.panes.detail,'esc');
  await s.waitVisible(s.panes.detail,'Start here');
  await terminal.resize(110,29);
  await s.waitFor('short narrow reader actually resized',()=>s.visible(s.panes.detail),f=>f.includes('Start here')&&f.trimEnd().split('\n').length<=12&&f.trimEnd().split('\n').every(line=>visibleWidth(line)<=40));
  await s.checkpoint('04-narrow-detail');
  await s.keys(s.panes.detail,'?');
  await s.waitVisible(s.panes.detail,'Find:');
  await s.keys(s.panes.detail,'esc');
  await s.renamePane(s.panes.detail,'My reader');
  await s.waitFor('manual label wins',()=>s.panePresentation(s.panes.detail),pane=>pane.label==='My reader'&&!pane.title);
  await s.waitFor('custom name visible in host frame',()=>terminal.visible(),f=>f.includes('My reader'));
  await s.waitFor('fallback identity remains in app',()=>s.visible(s.panes.detail),f=>f.split('\n')[0]!.includes('Current ·'));
  await s.checkpoint('05-manual-name-fallback');
  await terminal.resize(180,80);
  await s.focus(s.panes.tree);
  await s.revealTree(s.panes.tree,note.id);
  await s.keys(s.panes.tree,'?');
  await s.waitVisible(s.panes.tree,'Find:');
  await s.text(s.panes.tree,'Dock Preview below');
  await s.waitVisible(s.panes.tree,'Find: Dock Preview below');
  await s.keys(s.panes.tree,'enter');
  await s.waitFor('docking menu closed',()=>s.visible(s.panes.tree),f=>!f.includes('Find:')&&f.includes('Preview ·'));
  await s.waitFor('Tree and Preview compact composition',()=>s.visible(s.panes.tree),f=>f.includes('Start here')&&!f.includes('physical blocks')&&!f.includes('Opens in:')&&!f.includes('Tab links'));
  await s.checkpoint('06-tree-bottom-preview');
  assert.notEqual((await s.panePresentation(s.panes.tree)).title,'CHROME READING PLAN');
  await s.renamePane(s.panes.detail,'Outliner Detail');
  await s.waitFor('application title returns after default label',()=>s.panePresentation(s.panes.detail),p=>p.title==='CHROME READING PLAN');
  await s.swapPanes(s.panes.detail,s.panes.tree);
  const readerPane=s.panes.detail; // Herdr swaps positions, retaining pane identity.
  await s.waitFor('title follows swapped reader',()=>s.panePresentation(readerPane),p=>p.title==='CHROME READING PLAN');
  const alternate=await s.client.request<Block>({action:'create',text:'LATEST READER TITLE\n\nLatest body.'});
  for(const blockId of [alternate.id,note.id,alternate.id]) await s.client.request({action:'ui.command.send',command:{command:'open',targetClientId:detail.clientId,target:{kind:'block',blockId}}});
  await s.waitVisible(readerPane,'Latest body.');
  await s.waitFor('latest navigation wins host title',()=>s.panePresentation(readerPane),p=>p.title==='LATEST READER TITLE');
  await s.checkpoint('07-swapped-reader-latest-title');
  const after = await s.client.request<Block>({action:'get',blockId:note.id});
  assert.equal(after.text,note.text); assert.equal(after.revision,note.revision);
}});
console.log(JSON.stringify(result));
if(result.status!=='passed')process.exitCode=1;
