import assert from "node:assert/strict";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { visibleWidth } from "@earendil-works/pi-tui";
import type { AnnotationThread, Block, InternResourceReceipt, ResourceDescription, VisibleBlockCollection } from "../../src/types";
import { runHerdrScenario } from "./herdr-runner";

const result = await runHerdrScenario({
  name: "composed-surface", layout: "composed",
  async prepare(root) { await writeFile(join(root, "reference.md"), "Reference source\n\nSELECTABLE-FILE-QUOTE\n"); },
  async run(session) {
    const terminal = await session.attachClient();
    const pane = session.panes.tree;
    const goto = async (id: string) => {
      await session.keys(pane, "g");
      await session.waitFor("Goto popup", () => terminal.visible(), text => text.includes("Go to  "));
      await terminal.write(`\x1b[200~${id}\x1b[201~\r`);
      await session.waitFor("Goto popup closed", () => terminal.visible(), text => !text.includes("Go to  "));
    };
    assert.equal(pane, session.panes.detail);
    const registrations = await session.registrations();
    assert.equal(registrations.length, 1);
    const primary = registrations[0]!;
    assert.equal(primary.role, "composed");
    const reference = await session.client.request<Block>({action: "create", parentId: null, text: "PIE283 detached reference\n\nDetached canonical bytes"});
    for (let index = 0; index < 55; index++) await session.client.request({action: "create", parentId: null, text: `PIE283 scroll row ${index}`});
    const host = await session.client.request<Block>({action: "create", parentId: null, text: `PIE283 editing target\n\n((${reference.id}))\n\nOriginal body`});
    await session.focus(pane);
    await goto(host.id);
    await session.waitVisible(pane, "Original body");
    await session.keys(pane, "enter");
    await session.waitFor("primary Detail focus", session.registrations, values => values[0]?.focusedRegion === "detail");
    const opened = (await session.registrations())[0]!;
    assert.equal(opened.treeSelection?.target.kind, "block");
    const treeSelection = opened.treeSelection;
    const treeFrame = (await session.visible(pane)).split("\n").filter(line => line.includes("PIE283 scroll row")).map(line => line.slice(0, 31));
    assert.ok(treeFrame.length > 0);
    await session.checkpoint("01-selected-open-local");
    await session.keys(pane, "e");
    await session.waitVisible(pane, "Locked for editing");
    await terminal.write("\u001b[F");
    await session.text(pane, " edited");
    await session.waitVisible(pane, "Original body edited");
    await terminal.write("\u001a");
    await session.waitFor("undo draft", () => session.visible(pane), frame => !frame.includes("Original body edited"));
    await terminal.write("\u0019");
    await session.waitVisible(pane, "Original body edited");
    await terminal.write("\u001b[17~");
    await session.waitFor("Tree focus with dirty Detail", session.registrations, entries => entries[0]?.focusedRegion === "tree");
    await terminal.write("\u001b[17~");
    await session.waitFor("Detail focus restored", session.registrations, entries => entries[0]?.focusedRegion === "detail");
    await session.waitVisible(pane, "Original body edited");
    await terminal.write("\u0011");
    await session.waitVisible(pane, "Finish or cancel the draft");
    await terminal.write("\u0013");
    await session.waitFor("saved through existing editor", () => session.client.request<Block>({action: "get", blockId: host.id}), value => value.text.endsWith(" edited"));
    await session.checkpoint("02-saved-editor");
    await session.keys(pane, "q");
    await session.waitFor("local return to Tree", session.registrations, entries => entries[0]?.focusedRegion === "tree");
    assert.deepEqual((await session.registrations())[0]!.treeSelection, treeSelection);
    assert.deepEqual((await session.visible(pane)).split("\n").filter(line => line.includes("PIE283 scroll row")).map(line => line.slice(0, 31)), treeFrame);
    await terminal.write("\u001b[17~");
    await session.keys(pane, "e");
    await session.waitVisible(pane, "Locked for editing");
    await session.text(pane, " CANCELLED-BY-USER");
    await terminal.write("\u001b");
    await session.waitFor("cancel preview", () => session.visible(pane), frame => !frame.includes("CANCELLED-BY-USER"));
    assert.ok(!(await session.client.request<Block>({action: "get", blockId: host.id})).text.includes("CANCELLED-BY-USER"));
    await terminal.resize(100, 32);
    await session.waitFor("narrow frame", () => session.visible(pane), frame => frame.split("\n")[0]!.length < 70);
    await session.checkpoint("03-narrow-preserved");
    await terminal.resize(360, 60);
    await session.waitFor("wide frame", () => session.visible(pane), frame => frame.split("\n")[0]!.length > 120);
    await terminal.write("\u001b[17~");
    await session.waitFor("wide Detail focus", session.registrations, entries => entries[0]?.focusedRegion === "detail");
    await session.keys(pane, "e");
    await session.waitVisible(pane, "Draft ·");
    await session.checkpoint("04-wide-existing-draft-split");
    await terminal.write("\u001b");

    // Host discovery is an independent transport; local navigation must not need it.
    await session.waitFor("wide cancel returns Tree", session.registrations, entries => entries[0]?.focusedRegion === "tree");
    await terminal.write("\u001b[17~");
    await session.waitFor("Detail focus before unlock", session.registrations, entries => entries[0]?.focusedRegion === "detail");
    await session.keys(pane, "L");
    await session.waitFor("unlocked", session.registrations, entries => entries[0]?.locked === false);
    await session.setRegistryUnavailable(true);
    await session.waitFor("registry unavailable", session.registrations, entries => !entries[0]?.runtime?.paneId);
    assert.equal((await session.client.request<{status: string}>({action: "ping"})).status, "ready");
    await session.keys(pane, "q");
    await goto(reference.id);
    await session.waitVisible(pane, "Detached canonical bytes");
    await session.keys(pane, "enter", "e");
    await session.waitVisible(pane, "Locked for editing");
    await session.text(pane, " during registry outage");
    await terminal.write("\u0013");
    await session.waitFor("saved without discovery", () => session.client.request<Block>({action: "get", blockId: reference.id}), block => block.text.endsWith(" during registry outage"));
    await session.checkpoint("05-local-without-discovery");
    await session.setRegistryUnavailable(false);
    await session.waitFor("registry restored", session.registrations, entries => entries[0]?.runtime?.paneId === pane);

    // Explicit agent commands name the internal region, not merely the host pane.
    await session.client.request({action: "ui.command.send", command: {targetClientId: primary.clientId, targetRegion: "tree", command: "reveal", target: {kind: "block", blockId: host.id}}});
    await session.waitFor("agent Tree reveal", session.registrations, entries => entries[0]?.focusedRegion === "tree" && entries[0]?.treeSelection?.target.kind === "block" && entries[0]?.treeSelection.target.blockId === host.id);
    const splitIdentity = (await session.registrations())[0]!;
    assert.equal(splitIdentity.currentTarget?.kind, "block");
    if (splitIdentity.currentTarget?.kind === "block") assert.equal(splitIdentity.currentTarget.blockId, reference.id);
    await session.client.request({action: "ui.command.send", command: {targetClientId: primary.clientId, targetRegion: "detail", command: "replace", target: {kind: "block", blockId: host.id}}});
    await session.waitVisible(pane, "Original body edited");
    await session.keys(pane, "o");
    await session.waitVisible(pane, "Choose destination");
    await session.keys(pane, "r");
    const detachedRegistration = await session.waitFor("explicit detached Detail", session.registrations, entries => entries.length === 2);
    const detached = detachedRegistration.find(entry => entry.clientId !== primary.clientId)!;
    const detachedPane = await session.adoptDetached(detached.clientId);
    await session.waitVisible(detachedPane, "during registry outage");
    const beforeDetach = (await session.registrations()).find(entry => entry.clientId === primary.clientId)!;
    await session.checkpoint("06-detached-beside-primary");
    await session.moveDetachedToNewTab(detachedPane);
    await session.closeDetached(detachedPane);
    await session.waitFor("detached closed", session.registrations, entries => entries.length === 1);
    const afterDetach = (await session.registrations())[0]!;
    assert.deepEqual(afterDetach.currentTarget, beforeDetach.currentTarget);
    assert.deepEqual(afterDetach.treeSelection, beforeDetach.treeSelection);
    assert.ok((await session.client.request<Block>({action: "get", blockId: reference.id})).text.endsWith(" during registry outage"));
    await session.record("detached-preserves-primary-and-data", {beforeDetach, afterDetach});
    await session.focus(pane);

    const {resource} = await session.client.request<InternResourceReceipt>({action: "resources.intern-filesystem", input: {path: "reference.md"}});
    const description = await session.client.request<ResourceDescription>({action: "resources.describe", destinationClientId: primary.clientId, target: {kind: "resource", resourceId: resource.id}});
    assert.ok(description.filesystem);
    await session.client.request({action: "ui.command.send", command: {targetClientId: primary.clientId, targetRegion: "detail", command: "replace", target: {kind: "resource", resourceId: resource.id, revision: description.filesystem.revision}}});
    await session.waitVisible(pane, "SELECTABLE-FILE-QUOTE");
    const retained = (await session.registrations())[0]!;
    assert.deepEqual(retained.currentTarget, {kind: "resource", resourceId: resource.id, revision: description.filesystem.revision});
    assert.deepEqual(retained.treeSelection, afterDetach.treeSelection);
    await session.checkpoint("07-resource-retained-independent-of-tree");

    // Native pointer coordinates pass through Herdr and Pi's nested layout.
    const frame = await terminal.visible();
    const lines = frame.split("\n");
    const row = lines.findIndex(line => line.includes("SELECTABLE-FILE-QUOTE"));
    assert.ok(row >= 0);
    const column = visibleWidth(lines[row]!.slice(0, lines[row]!.indexOf("SELECTABLE-FILE-QUOTE")));
    const quote = "SELECTABLE-FILE-QUOTE";
    await terminal.write(`\u001b[<0;${column + 1};${row + 1}M`);
    await terminal.write(`\u001b[<32;${column + quote.length + 1};${row + 1}M`);
    await terminal.write(`\u001b[<0;${column + quote.length + 1};${row + 1}m`);
    await session.keys(pane, "c");
    await session.waitVisible(pane, "Comment on Resource selection");
    await session.text(pane, "PIE283 native pointer comment");
    await terminal.write("\u0013");
    const annotations = await session.waitFor("native selection comment saved", () => session.client.request<VisibleBlockCollection>({action: "blocks.query", query: {text: "PIE283 native pointer comment", filters: [{key: "type", value: "annotation"}], limit: 2}}), rows => rows.blocks.length === 1);
    const annotation = await session.client.request<AnnotationThread>({action: "annotations.get", annotationId: annotations.blocks[0]!.id});
    assert.equal(annotation.originalTarget.representation.subject.kind, "resource");
    assert.equal(annotation.originalTarget.anchor.kind, "text-quote");
    if (annotation.originalTarget.anchor.kind !== "text-quote") throw new Error("Expected source quote");
    assert.equal(annotation.originalTarget.anchor.exact, quote);
    assert.equal(annotation.originalTarget.anchor.start, "Reference source\n\n".length);
    await session.record("source-coordinate-proof", {row, column, annotation});
    await session.checkpoint("08-source-selection-comment");
  },
});
console.log(JSON.stringify(result));
if (result.status !== "passed") process.exitCode = 1;
