import {visibleWidth} from '@earendil-works/pi-tui';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import type {Block} from '../../src/types';
import type {MentionCollection} from '../../src/mentions-types';
import {runHerdrScenario} from './herdr-runner';

const result=await runHerdrScenario({name:'recent-mentions',async prepare(){},async run(session){
 const terminal=await session.attachClient();
 const alpha=await session.client.request<Block>({action:'create',text:'Mention Alpha [page::mention-alpha]\n\nALPHA CANONICAL BODY'});
 const beta=await session.client.request<Block>({action:'create',text:'Mention Beta\n\nBETA CANONICAL BODY'});
 await session.client.request({action:'work-ids.configure',prefix:'PIE'});
 await session.client.request({action:'work-ids.allocate',blockId:alpha.id,expectedRevision:alpha.revision});
 const wrapper=join(session.artifactDirectory,'notify-wrapper.ts');
 await writeFile(wrapper,`import {writeFile} from 'node:fs/promises';
await writeFile(${JSON.stringify(join(session.artifactDirectory,'notify-event.json'))},process.argv.at(-1)!);
const child=Bun.spawn(${JSON.stringify([process.execPath,resolve('src/mentions-codex.ts'),'--workspace',session.projectRoot])}.concat(process.argv.at(-1)!),{env:process.env,stdout:'pipe',stderr:'pipe'});
await writeFile(${JSON.stringify(join(session.artifactDirectory,'notify-adapter.txt'))},await new Response(child.stderr).text());
await child.exited;`);
 const notify=[process.execPath,wrapper];
 const final=`Read [[mention-alpha]] and PIE-001, then ${beta.id}.`;
 const child=Bun.spawn(['codex','exec','--ephemeral','--skip-git-repo-check','-C',session.projectRoot,'-c',`notify=${JSON.stringify(notify)}`,'--json',`This is a completed-response integration check. Do not use tools or inspect files. Reply with precisely this one sentence: ${final}`],{env:{...process.env,OUTLINER_REMOTE:"1",OUTLINER_SOCKET_PATH:session.client.socketPath},stdout:'pipe',stderr:'pipe'});
 const timer=setTimeout(()=>child.kill(),90000);
 const [stdout,stderr,code]=await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);clearTimeout(timer);
 await writeFile(join(session.artifactDirectory,'codex-completion.jsonl'),stdout);
 await writeFile(join(session.artifactDirectory,'codex-stderr.txt'),stderr);
 assert.equal(code,0,stderr);
 const found=await session.waitFor('real Codex completed response',()=>session.client.request<MentionCollection>({action:'mentions.list'}),value=>value.entries.length===2);
 assert.deepEqual(found.entries.map(e=>e.block?.id),[alpha.id,beta.id]);
 await session.record('completed-agent-mentions',found);
 await session.setKeybindings({'tree.mentions.open':['Alt+M']});
 await session.keys(session.panes.tree,'ctrl+r');await session.waitVisible(session.panes.tree,'Outliner keymap reloaded');
 await session.keys(session.panes.tree,'alt+m');
 const wait=(label:string)=>session.waitFor(label,terminal.visible,text=>text.includes(label));
 await wait('Recent mentions');await wait('ALPHA CANONICAL BODY');
 await terminal.write('m');await wait('Completed message');
 await terminal.write('s');await wait('codex conversation');
 await terminal.write('v');await wait('Saved completed message to Inbox');
 await terminal.write('m');await wait('ALPHA CANONICAL BODY');
 await terminal.write('\x1b[B');await wait('BETA CANONICAL BODY');
 await session.checkpoint('canonical-preview-and-context');
 await terminal.write('\r');await wait('Choose destination');
 await session.checkpoint('explicit-destination');
 await terminal.write('\r');await session.waitVisible(session.panes.detail,'BETA CANONICAL BODY');
 await session.focus(session.panes.tree);await session.keys(session.panes.tree,'alt+m');await wait('Recent mentions');
 // Mouse controls use the same command path; Clear never deletes canonical notes.
 const frame=(await wait('[c Clear]')).split('\n'),row=frame.findIndex(line=>line.includes('[c Clear]'));
 const column=visibleWidth(frame[row]!.slice(0,frame[row]!.indexOf('[c Clear]')))+2;
 await terminal.write(`\x1b[<0;${column};${row+1}M\x1b[<0;${column};${row+1}m`);await wait('Cleared 1 retained messages');
 assert.equal((await session.client.request<MentionCollection>({action:'mentions.list'})).entries.length,0);
 assert.equal((await session.client.request<Block>({action:'get',blockId:beta.id})).text,beta.text);
 await session.checkpoint('cleared-history');
 await terminal.write('q');
}});
console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1;
