import assert from 'node:assert/strict';
import {visibleWidth} from '@earendil-works/pi-tui';
import type {Block} from '../../src/types';
import {runHerdrScenario} from './herdr-runner';
const result=await runHerdrScenario({name:'reference-completion',async prepare(){},async run(s){
 const terminal=await s.attachClient();await terminal.resize(240,65);
 await s.client.request<Block>({action:'create',text:'Project Alpha [page::alpha-plan]\n\nDelivery plan for the daily work.'});
 await s.client.request<Block>({action:'create',text:'Project Alpha [page::alpha-context]\n\nResearch context for daily work.'});
 const source=await s.client.request<Block>({action:'create',text:'WRITING HOME\n\nA note that stays while choosing.'});
 await s.revealTree(s.panes.tree,source.id);await s.keys(s.panes.tree,'enter');await s.waitVisible(s.panes.detail,'WRITING HOME');
 await s.keys(s.panes.detail,'e','alt+a');await s.text(s.panes.detail,'WRITING HOME\n\nBefore [[alpha');await s.waitVisible(s.panes.detail,'References');
 await s.checkpoint('01-inline-results');
 await s.text(s.panes.detail,'-plan');await s.waitVisible(s.panes.detail,'References 1/1');await s.keys(s.panes.detail,'enter');
 await s.keys(s.panes.detail,'ctrl+s');await s.waitFor('canonical keyboard insertion',()=>s.client.request<Block>({action:'get',blockId:source.id}),b=>b.text==='WRITING HOME\n\nBefore [[alpha-plan]]');
 await s.keys(s.panes.detail,'e','alt+a');await s.text(s.panes.detail,'WRITING HOME\n\nMouse [[alpha-context');await s.waitVisible(s.panes.detail,'References 1/1');
 const frame=await s.waitFor('attached context candidate',terminal.visible,t=>t.includes('alpha-context — Project Alpha'));
 const lines=frame.split('\n'),row=lines.findIndex(l=>l.includes('alpha-context — Project Alpha')),col=visibleWidth(lines[row]!.slice(0,lines[row]!.indexOf('alpha-context — Project Alpha')))+2;
 await terminal.write(`\x1b[<0;${col+1};${row+1}M\x1b[<0;${col+1};${row+1}m`);
 await s.waitVisible(s.panes.detail,'[[alpha-context]]');await s.keys(s.panes.detail,'ctrl+z');await s.waitFor('undo removes insertion',()=>s.visible(s.panes.detail),t=>t.includes('Mouse [[alpha-context')&&!t.includes('[[alpha-context]]'));await s.keys(s.panes.detail,'ctrl+y');await s.waitVisible(s.panes.detail,'[[alpha-context]]');await s.keys(s.panes.detail,'ctrl+s');await s.waitFor('canonical pointer insertion',()=>s.client.request<Block>({action:'get',blockId:source.id}),b=>b.text==='WRITING HOME\n\nMouse [[alpha-context]]');
 await s.checkpoint('02-pointer-insert');
 await s.keys(s.panes.detail,'e','alt+a');await s.text(s.panes.detail,'WRITING HOME\n\nKeep this [[alpha');await s.waitVisible(s.panes.detail,'References');await s.keys(s.panes.detail,'escape');await s.text(s.panes.detail,' remains');
 await s.keys(s.panes.detail,'ctrl+s');const saved=await s.waitFor('dismiss preserves draft',()=>s.client.request<Block>({action:'get',blockId:source.id}),b=>b.text.includes(' remains'));assert.ok(saved.text.includes('Keep this [[alpha remains'));
 await s.checkpoint('03-dismiss-and-continue');
 const blockTarget=await s.client.request<Block>({action:'create',text:'BLOCK DESTINATION\n\nThis context disambiguates the block.'});
 const quick=await s.client.request<Block>({action:'create',text:'TREE WRITING ((BLOCK DEST'});
 await s.revealTree(s.panes.tree,quick.id);await s.keys(s.panes.tree,'e','tab');await s.waitVisible(s.panes.tree,'References');await s.waitVisible(s.panes.tree,'BLOCK DESTINATION');
 await s.keys(s.panes.tree,'enter','enter');await s.waitFor('Tree canonical block insertion',()=>s.client.request<Block>({action:'get',blockId:quick.id}),b=>b.text===`TREE WRITING ((${blockTarget.id}))`);
 await terminal.resize(130,45);await s.keys(s.panes.tree,'e','alt+a');await s.text(s.panes.tree,'TREE WRITING [[alpha');await s.keys(s.panes.tree,'tab');await s.waitVisible(s.panes.tree,'References');
 await s.checkpoint('04-narrow-tree-completion');await s.keys(s.panes.tree,'escape','escape');
 assert.equal((await s.client.request<Block>({action:'get',blockId:quick.id})).text,`TREE WRITING ((${blockTarget.id}))`);
}});console.log(JSON.stringify(result));if(result.status!=='passed')process.exitCode=1;
